version: '2'
services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "9229:9229"
      - "9222:9222"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://alphabeta:alphabeta@db:5432/alphabeta
      DATABASE_USER: alphabeta
      DATABASE_NAME: alphabeta
      DATABASE_PASSWORD: alphabeta
  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: alphabeta
      POSTGRES_DB: alphabeta
      POSTGRES_PASSWORD: alphabeta
    ports:
      - 5432:5432
    # Use this to persist your database data on your local drive
    volumes:
      - galene:/var/lib/postgresql/data

volumes:
  galene: